# This is a basic workflow to help you get started with Actions

name: RUN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install python stuff and activate virtual environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install -r requirements.txt

      - name: Build main website
        run: pipenv run sphinx-build docs build/html

      - name: Build scenarios
        run:  for d in $(ls -d scenarios/*); do pipenv run sphinx-build $d build/html/$d; done

      - name: Upload website to artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/html'
          
      - name: Publish website at GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1
